config:
  line_length: # MD013
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
globs:
  - "posts/**/*.qmd"
  - "*.qmd"
ignores:
  - "_site/**/*.qmd"
  - ".github/ISSUE_TEMPLATE/meeting_setup.md"

fix: true
